### ISSUE TITLE
Permission Denied when trying to run reaction_reaction_1 container

### ISSUE THREAD

**Issue by slavikme** [reactioncommerce/reaction-development-platform#54]
## Issue Description
After clean ubuntu install, did everything as guided [here](https://docs.reactioncommerce.com/docs/installation-reaction-platform#installation). The 
`make` command successfully finished without any errors.

When I did `docker ps -a`, I noticed that only 3 out of 6 containers are running.
```
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                      PORTS                                                      NAMES
09fbfb956e44        reaction-next-starterkit_web      "/usr/local/src/reac…"   13 minutes ago      Exited (1) 13 minutes ago                                                              reaction-next-starterkit_web_1
db959c6740c2        reaction_reaction                 "bash -c 'time meteo…"   14 minutes ago      Exited (1) 14 minutes ago                                                              reaction_reaction_1
424bfbbd092b        mongo:3.6.3                       "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes               0.0.0.0:27017->27017/tcp                                   reaction_mongo_1
e95980338b91        oryd/hydra:v1.0.0-beta.9-alpine   "hydra serve all --d…"   19 minutes ago      Up 19 minutes               0.0.0.0:4444-4445->4444-4445/tcp, 0.0.0.0:5555->5555/tcp   reaction-hydra_hydra_1
c4d74ea130d5        oryd/hydra:v1.0.0-beta.9-alpine   "hydra migrate sql -e"   19 minutes ago      Exited (0) 19 minutes ago                                                              reaction-hydra_hydra-migrate_1
```

I ran `docker-compose logs` for both `reaction` and `reaction-next-starterkit`. I saw that the issue is something with permissions.

```
$ docker-compose logs
web_1  | yarn install v1.13.0
web_1  | [1/4] Resolving packages...
web_1  | [2/4] Fetching packages...
web_1  | error An unexpected error occurred: "https://registry.yarnpkg.com/brcast/-/brcast-3.0.1.tgz: EACCES: permission denied, open '/home/node/.cache/yarn-offline-mirror/brcast-3.0.1.tgz'".
web_1  | info If you think this is a bug, please open a bug report with the information provided in "/usr/local/src/reaction-app/yarn-error.log".
web_1  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
reaction-next-starterkit_web_1 exited with code 1
```
```
reaction_1  | Setting up plugin imports...
reaction_1  | 
reaction_1  | Setting up plugin imports took 0s 17.152383ms
reaction_1  | 
reaction_1  | Setting up style imports...
reaction_1  | 
reaction_1  | Setting up style imports took 0s 6.676314ms
reaction_1  | 
reaction_1  | Provisioning assets...
reaction_1  | 
reaction_1  | Provisioning assets took 0s 11.513272ms
reaction_1  | 
reaction_1  | Running command: meteor run --no-lint --no-release-check --raw-logs 
reaction_1  | /home/node/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
reaction_1  |       throw error;
reaction_1  |       ^
reaction_1  | 
reaction_1  | Error: EACCES: permission denied, open '/opt/reaction/src/.meteor/local/.resolver-result-cache.json.1uocjx9.c6vi'
reaction_1  |     at Object.fs.openSync (fs.js:646:18)
reaction_1  |     at Object.fs.writeFileSync (fs.js:1299:33)
reaction_1  |     at Object.wrapper [as writeFile] (/tools/fs/files.js:1609:35)
reaction_1  |     at Object.writeFileAtomically (/tools/fs/files.js:1071:11)
reaction_1  |     at ProjectContext._saveResolverResultCache (/tools/project-context.js:619:11)
reaction_1  |     at /tools/project-context.js:594:14
reaction_1  |     at Object.enterJob (/tools/utils/buildmessage.js:388:12)
reaction_1  |     at /tools/project-context.js:529:20
reaction_1  |     at /tools/packaging/catalog/catalog.js:100:5
reaction_1  |     at Object.capture (/tools/utils/buildmessage.js:283:5)
reaction_1  |     at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
reaction_1  |     at ProjectContext._resolveConstraints (/tools/project-context.js:528:13)
reaction_1  |     at /tools/project-context.js:300:9
reaction_1  |     at Object.enterJob (/tools/utils/buildmessage.js:388:12)
reaction_1  |     at ProjectContext._completeStagesThrough (/tools/project-context.js:290:18)
reaction_1  |     at Profile.run (/tools/project-context.js:260:12)
reaction_1  |     at Function.run (/tools/tool-env/profile.js:490:12)
reaction_1  |     at ProjectContext.resolveConstraints (/tools/project-context.js:259:13)
reaction_1  |     at /tools/runners/run-all.js:75:27
reaction_1  |     at Object.capture (/tools/utils/buildmessage.js:283:5)
reaction_1  |     at new Runner (/tools/runners/run-all.js:74:18)
reaction_1  |     at Object.exports.run (/tools/runners/run-all.js:366:16)
reaction_1  |     at Command.doRunCommand [as func] (/tools/cli/commands.js:417:17)
reaction_1  |     at /tools/cli/main.js:1531:15
reaction_1  | { Error: Command failed: REACTION_METEOR_APP_COMMAND_START_TIME=1552795323936 meteor run --no-lint --no-release-check --raw-logs 
reaction_1  |     at checkExecSyncError (child_process.js:601:13)
reaction_1  |     at Object.execSync (child_process.js:641:13)
reaction_1  |     at run (file:///opt/reaction/src/.reaction/run/index.mjs:41:18)
reaction_1  |     at file:///opt/reaction/src/.reaction/run/index.mjs:49:1
reaction_1  |     at ModuleJob.run (internal/loader/ModuleJob.js:97:14)
reaction_1  |     at <anonymous>
reaction_1  |   error: null,
reaction_1  |   cmd: 'REACTION_METEOR_APP_COMMAND_START_TIME=1552795323936 meteor run --no-lint --no-release-check --raw-logs ',
reaction_1  |   file: '/bin/sh',
reaction_1  |   args: 
reaction_1  |    [ '/bin/sh',
reaction_1  |      '-c',
reaction_1  |      'REACTION_METEOR_APP_COMMAND_START_TIME=1552795323936 meteor run --no-lint --no-release-check --raw-logs ' ],
reaction_1  |   options: 
reaction_1  |    { stdio: [ [Object], [Object], [Object] ],
reaction_1  |      shell: true,
reaction_1  |      file: '/bin/sh',
reaction_1  |      args: 
reaction_1  |       [ '/bin/sh',
reaction_1  |         '-c',
reaction_1  |         'REACTION_METEOR_APP_COMMAND_START_TIME=1552795323936 meteor run --no-lint --no-release-check --raw-logs ' ],
reaction_1  |      envPairs: 
reaction_1  |       [ 'TOOL_NODE_FLAGS=',
reaction_1  |         'NODE_VERSION=8.11.4',
reaction_1  |         'HOSTNAME=db959c6740c2',
reaction_1  |         'METEOR_WATCH_POLLING_INTERVAL_MS=10000',
reaction_1  |         'METEOR_VERSION=1.8.0.2',
reaction_1  |         'METEOR_DISABLE_OPTIMISTIC_CACHING=1',
reaction_1  |         'REACTION_EMAIL=admin@localhost',
reaction_1  |         'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor:/opt/reaction/src/node_modules/.bin',
reaction_1  |         'PWD=/opt/reaction/src',
reaction_1  |         'MONGO_URL=mongodb://mongo:27017/reaction',
reaction_1  |         'REACTION_USER=Admin',
reaction_1  |         'APP_BUNDLE_DIR=/opt/reaction/dist',
reaction_1  |         'ROOT_URL=http://localhost:3000',
reaction_1  |         'HYDRA_TOKEN_URL=http://hydra:4444/oauth2/token',
reaction_1  |         'SHLVL=1',
reaction_1  |         'HOME=/home/node',
reaction_1  |         'REACTION_AUTH=r3@cti0n',
reaction_1  |         'YARN_VERSION=1.6.0',
reaction_1  |         'OAUTH2_CLIENT_DOMAINS=http://localhost:4000',
reaction_1  |         'REACTION_DOCKER_BUILD=true',
reaction_1  |         'REACTION_USER_NAME=admin',
reaction_1  |         'REACTION_SECURE_DEFAULT_ADMIN=false',
reaction_1  |         'APP_SOURCE_DIR=/opt/reaction/src',
reaction_1  |         'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
reaction_1  |         'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
reaction_1  |         'HYDRA_ADMIN_URL=http://hydra:4445',
reaction_1  |         'IDENTITY_PROVIDER_MODE=all',
reaction_1  |         '_=/usr/local/bin/node' ],
reaction_1  |      killSignal: undefined },
reaction_1  |   envPairs: 
reaction_1  |    [ 'TOOL_NODE_FLAGS=',
reaction_1  |      'NODE_VERSION=8.11.4',
reaction_1  |      'HOSTNAME=db959c6740c2',
reaction_1  |      'METEOR_WATCH_POLLING_INTERVAL_MS=10000',
reaction_1  |      'METEOR_VERSION=1.8.0.2',
reaction_1  |      'METEOR_DISABLE_OPTIMISTIC_CACHING=1',
reaction_1  |      'REACTION_EMAIL=admin@localhost',
reaction_1  |      'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor:/opt/reaction/src/node_modules/.bin',
reaction_1  |      'PWD=/opt/reaction/src',
reaction_1  |      'MONGO_URL=mongodb://mongo:27017/reaction',
reaction_1  |      'REACTION_USER=Admin',
reaction_1  |      'APP_BUNDLE_DIR=/opt/reaction/dist',
reaction_1  |      'ROOT_URL=http://localhost:3000',
reaction_1  |      'HYDRA_TOKEN_URL=http://hydra:4444/oauth2/token',
reaction_1  |      'SHLVL=1',
reaction_1  |      'HOME=/home/node',
reaction_1  |      'REACTION_AUTH=r3@cti0n',
reaction_1  |      'YARN_VERSION=1.6.0',
reaction_1  |      'OAUTH2_CLIENT_DOMAINS=http://localhost:4000',
reaction_1  |      'REACTION_DOCKER_BUILD=true',
reaction_1  |      'REACTION_USER_NAME=admin',
reaction_1  |      'REACTION_SECURE_DEFAULT_ADMIN=false',
reaction_1  |      'APP_SOURCE_DIR=/opt/reaction/src',
reaction_1  |      'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
reaction_1  |      'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
reaction_1  |      'HYDRA_ADMIN_URL=http://hydra:4445',
reaction_1  |      'IDENTITY_PROVIDER_MODE=all',
reaction_1  |      '_=/usr/local/bin/node' ],
reaction_1  |   stderr: null,
reaction_1  |   stdout: null,
reaction_1  |   pid: 62,
reaction_1  |   output: [ null, null, null ],
reaction_1  |   signal: null,
reaction_1  |   status: 1 }
reaction_1  | 
reaction_1  | Error: App failed to start
reaction_reaction_1 exited with code 1
```

Have managed to solve the issue with the `reaction-next-starterkit_web_1` container with a tip from here, but I have no idea how to fix the `reaction_reaction_1` container issues.

Can you please help me?

## Steps to Reproduce
Exactly as described in this guide: https://docs.reactioncommerce.com/docs/installation-reaction-platform#installation

### Versions
Ubuntu Server 18.10
```
$ uname -a
Linux 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by HikvIneH** [comment]
You can change the permission of /opt/reaction/src/.meteor on the docker.
```
docker start reaction_reaction_1 && docker exec -it --user root reaction_reaction_1 chown -R node:node /opt/reaction/src/.meteor
```

**Comment by slavikme** [comment]
Thanks, it worked.

I wonder, why it happened in the first place? I mean, since it's a clean installation, shouldn't it be noticeable to the community? Am I the only one that experiencing it? Because it looks like a bug to me.

I would be happy to help with whatever I can to resolve this bug.

**Comment by maxbaluev** [comment]
I have same problem with clean installation

**Comment by maxbaluev** [comment]
@HikvIneH how solve problem with reaction-next-starterkit container ?

`Starting reaction-next-starterkit_web_1 ... done
Attaching to reaction-next-starterkit_web_1
web_1  | yarn install v1.13.0
web_1  | [1/4] Resolving packages...
web_1  | [2/4] Fetching packages...
web_1  | error An unexpected error occurred: "https://registry.yarnpkg.com/brcast/-/brcast-3.0.1.tgz: EACCES: permission denied, open '/home/node/.cache/yarn-offline-mirror/brcast-3.0.1.tgz'".
web_1  | info If you think this is a bug, please open a bug report with the information provided in "/usr/local/src/reaction-app/yarn-error.log".
web_1  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
web_1  | yarn install v1.13.0
web_1  | [1/4] Resolving packages...
web_1  | [2/4] Fetching packages...
web_1  | error An unexpected error occurred: "https://registry.yarnpkg.com/classnames/-/classnames-2.2.6.tgz: EACCES: permission denied, open '/home/node/.cache/yarn-offline-mirror/classnames-2.2.6.tgz'".
web_1  | info If you think this is a bug, please open a bug report with the information provided in "/usr/local/src/reaction-app/yarn-error.log".
web_1  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
reaction-next-starterkit_web_1 exited with code 1`

**Comment by HikvIneH** [comment]
docker start reaction-next-starterkit_web_1 && docker exec -it --user
root reaction-next-starterkit_web_1 chown -R node:node /home/node

**Comment by NoShadock** [comment]
> I wonder, why it happened in the first place? I mean, since it's a clean installation, shouldn't it be noticeable to the community? Am I the only one that experiencing it? 

I had thought it was because I used `sudo make` at some point.

My fix was to change ownership for these files from root to $USER:
./reaction/.meteor/local
./reaction/node_modules
./reaction-next-starterkit/node_modules

(then `make start`)

I'd love to know how that happened.

**Comment by trentsteel777** [comment]
> You can change the permission of /opt/reaction/src/.meteor on the docker.
> 
> ```
> docker start reaction_reaction_1 && docker exec -it --user root reaction_reaction_1 chown -R node:node /opt/reaction/src/.meteor
> ```

I was also experiencing this issue on Ubunutu 16.04 LTS, running the above command along with the below has allowed me to start the project:
_docker start reaction_reaction_1 && docker exec -it --user root reaction_reaction_1 chown -R node:node /opt/reaction/src/.meteor_

**Comment by arimus** [comment]
Same issue here. The exec does appear to get past the issues, but now I ran into:

**Comment by arimus** [comment]
The way I was able to resolve this was a suggestion from another issue, which I can't seem to find now. Modify reaction/docker-compose.yml to comment out a couple lines and this container should work:

```
    volumes:
            #- .:/opt/reaction/src:cached
            #- ./.meteor/local:/opt/reaction/src/.meteor/local:delegated
      - reaction_node_modules:/opt/reaction/src/node_modules # do not link node_modules in, and persist it between dc up runs
```

You will likely have the container for reaction-next-starterkit give you another permissions issue. I ran the permissions change for that one with success, although I suspect you can probably modify the docker compose config as well:

```
docker start <container_id> && docker exec -it --user root <container_id> chown -R node:node /home/node /usr/local/src
```

where <container_id> is obtained form a `docker ps -a`

**Comment by gmartinsribeiro** [comment]
I'm having the same issue with a clean install

**Comment by wc-matteo** [comment]
Same here. Please fix this. It impacts the first experience one has with the platform

**Comment by RoytenBerge** [comment]
> > I wonder, why it happened in the first place? I mean, since it's a clean installation, shouldn't it be noticeable to the community? Am I the only one that experiencing it?
> 
> I had thought it was because I used `sudo make` at some point.
> 
> My fix was to change ownership for these files from root to $USER:
> ./reaction/.meteor/local
> ./reaction/node_modules
> ./reaction-next-starterkit/node_modules
> 
> (then `make start`)
> 
> I'd love to know how that happened.

Fixed it for me! Thanks

**Comment by aldeed** [comment]
Should have been fixed by UID fixing scripts we now run automatically.
